### ISSUE TITLE
Le code dépasse dans la documentation

### ISSUE THREAD

**Issue by MonsieurMan** [SNCFdevelopers/wcs#86]
Rajouter un scroll avec un code similaire : 
```css
.pre {
  overflow-x: scroll;
  background: var(--wcs-light);
  border-radius: var(--wcs-border-radius);
  padding: 16px;
}
```
